admin/src/containers/View/components/NavigationItemForm/index.js
services/navigation.js

Issue #2
_Relationship to Content Type" dropdown throws a 404 when collection names don't match endpoint ids_
Fixes a case when collection name doesn't match the api name like in the case:
- Collection name: `blog_posts`
- Api name: `blog-post`

fix: issue #2 - 404 for some collection endpoints

---

.github/pull_request_template.md
admin/src/components/Item/index.js
admin/src/components/ItemFooter/Wrapper.js
admin/src/components/ItemFooter/index.js
admin/src/components/ItemOrdering/CardOrderingButton.js
admin/src/components/ItemOrdering/Wrapper.js
admin/src/components/ItemOrdering/index.js
admin/src/components/List/index.js
admin/src/containers/View/index.js
admin/src/containers/View/utils/parsers.js
models/navigationItem.settings.json
package.json
services/navigation.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/4
Introduces the items ordering / re-ordering feature to the UI.
1. Add couple items within the navigation plugin editor
2. Change position of some items
3. Save
4. Reload and see that changes has been saved

feat: re-ordering navigation items

---

admin/src/containers/DataManagerProvider/index.js
admin/src/containers/View/utils/parsers.js

That PR will fix the problem with init components after the situation when we remove object in relation example:
1. Add an object to a relation
2. Add navigation and assign an object to the navigation item
3. remove object in relation
4. navigation not loaded correctly.

feat: fix problem with parsing after remove object in relation

---

admin/src/containers/View/components/NavigationItemForm/index.js
admin/src/containers/View/utils/parsers.js

`admin/src/containers/View/components/NavigationItemForm/index.js`
onChange is not used in component
`admin/src/containers/View/utils/parsers.js`
as in comment in the file here, we have some inconsistent data on fetch we got array but on edit, we get primitive type where is `isEmpty` returning true

feat: preventing stop assign relation on edit

---

README.md
__mocks__/helpers/blog-post.settings.json
__mocks__/helpers/page.settings.json
__mocks__/helpers/strapi.js
admin/src/components/Item/index.js
admin/src/components/ItemFooter/index.js
admin/src/components/List/index.js
admin/src/containers/View/components/NavigationItemForm/index.js
admin/src/containers/View/components/NavigationItemPopup/index.js
admin/src/containers/View/index.js
admin/src/containers/View/utils/parsers.js
jest.config.js
package.json
services/__tests__/navigation.test.js
services/navigation.js

None, reported by mail.
500 on GET Navigation (tree) and lack of possibility to setup titles for content types
Fixes issue with 500 error on GET Navigation (tree) and provided additional configuration for content types and their title fields. Also solves couple intermediate issues recognized during development.
First tests has been introduced.
Run it and check.

feat: configurable title fields for content types

---

admin/src/containers/View/utils/parsers.js
services/navigation.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/29
> Fix problems on mongo database, navigation items in response not contained correctly related entities.
Add navigation items and relation, in response, you should got correctly related entities.

fix: return related content type for mongo

---

examples/audit-log-integrations.js.md

make audit log example readable on GH
now: https://github.com/VirtusLab/strapi-plugin-navigation/blob/master/examples/audit-log-integrations.js.md
after merge this PR: https://github.com/VirtusLab/strapi-plugin-navigation/blob/fix/styling-audit-log-example/examples/audit-log-integrations.js.md

fix: styling audit log example

---

README.md
__mocks__/helpers/blog-post.settings.json
__mocks__/helpers/page.settings.json
admin/src/containers/View/utils/parsers.js
package.json
services/__tests__/navigation.test.js
services/navigation.js
services/utils/functions.js
yarn.lock

N/A
- fixes issue with render method for multipart content types names
- version bump
- dependencies bump for `strapi 3.5.0`
- try to fetch data from `navigation/render/<id or slug>` endpoint

fix: render should use uid instead of content type name

---

__mocks__/helpers/blog-post.settings.json
__mocks__/helpers/pages.settings.json
__mocks__/helpers/strapi.js
admin/src/components/Item/index.js
admin/src/components/List/index.js
admin/src/containers/View/components/NavigationItemForm/index.js
admin/src/containers/View/components/NavigationItemPopup/index.js
admin/src/containers/View/index.js
admin/src/containers/View/utils/parsers.js
package.json
services/__tests__/navigation.test.js
services/navigation.js
services/utils/functions.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/28
https://github.com/VirtusLab/strapi-plugin-navigation/issues/35
- changes the way if relations linking
- fixing the associations mismatch between SQL and noSQL databases
- run on any SQL database
- run on MondoDB
- see that all works

fix: use uid instead of collection name for linking

---

services/utils/functions.js

Change from single types being represented in navigation render as a default template to representing single type as a template itself.
- run on any SQL database
- run on MondoDB
- see that all works

feat: single type is a template for itself

---

README.md
__mocks__/helpers/pages.settings.json
admin/src/components/Item/index.js
admin/src/components/ItemFooter/CardItemError.js
admin/src/components/ItemFooter/CardItemRelationStatus.js
admin/src/components/ItemFooter/index.js
admin/src/components/List/index.js
admin/src/containers/DataManagerProvider/index.js
admin/src/containers/DataManagerProvider/reducer.js
admin/src/containers/DetailsView/index.js
admin/src/containers/ListView/index.js
admin/src/containers/View/components/NavigationItemForm/index.js
admin/src/containers/View/components/NavigationItemForm/utils/form.js
admin/src/containers/View/components/NavigationItemPopup/index.js
admin/src/containers/View/index.js
admin/src/containers/View/utils/parsers.js
admin/src/translations/en.json
admin/src/translations/index.js
package.json
services/__tests__/navigation.test.js
services/navigation.js
services/utils/functions.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/42
https://github.com/VirtusLab/strapi-plugin-navigation/issues/44
- adds coverage for built-in Strapi draft & publish flow
- prevents 500 error when content type entity has been accidentally removed
- filter outs removed and draft entities from render output
- play with single & collection types
- play with the publish status

fix: providing coverage for draft and publish Strapi content types

---

README.md
services/navigation.js
services/utils/functions.js

Template names support for a single type
- Create a single type if not present
- Provide data for single type
- Add navigation item pointing to a single type
- Render navigation
- Update override `templateName` in section `options` of `.settings.json` file 
- Render navigation

feat: support for templates on single types

---

README.md
admin/src/components/Select/index.js
admin/src/containers/DataManagerProvider/index.js
admin/src/containers/View/components/NavigationItemForm/index.js
package.json

N/A
- solves the issue while searching for content types (more than 100 instances)
- provides typeahead functionality for content types select
- run and play with the content type search

fix: content types search limit

---

package.json
services/navigation.js

N/A
- drops default Strapi query limits to support large navigations
- might be difficult to get more than 100 items, just play and check if nothing crash

fix: drop query limits in the service

---

admin/src/containers/View/utils/parsers.js

N/A
Reading audience item id in serialisation function.
In this specific place audienceItem is not an instance of strapi content type but value object coming from `react-select` component.
- add an audience
- try to add it to a navigation item
- save
- confirm that audience is saved

fix: audiences in transform for rest payload

---

README.md
config/functions/bootstrap.js
package.json

https://github.com/VirtusLab/strapi-plugin-navigation/issues/56
Changes bootstrap method to be compatible with `Strapi 3.6.x`
N/A

fix: compatibility with strapi 3.6.x

---

config/routes.json
controllers/navigation.js
services/navigation.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/76
Added an option to filter out the children by the `uiRouterKey` for all of the types.
There is an option to distinguish between id/slug for the flat type to use strapi filtration.
Base project with Postmann calls

Add option to render selected child of root nav

---

.circleci/config.yml
README.md
config/schema.graphql.js
controllers/navigation.js
services/navigation.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/54
Add GQL support
Example queries:
```gql
query {
renderNavigation(navigationIdOrSlug: "main-navigation", type: TREE) { 
id
title
type
path
externalPath
uiRouterKey
menuAttached
parent
master
related {
id
}
audience
items {
id
items {
id
}
}
items {
id
}
}
getNavigation {
id
name
slug
}
configNavigation {
allowedLevels
additionalFields
availableAudience {
id
name
}
contentTypesNameFields {
default
page
pages
}
contentTypes {
uid
name
collectionName
}
}
getByIdNavigation(id:"1"){
id
items {
id
items {
id
}
}
}
renderNavigationChild(id: "1", childUIKey: …
```

feat: add gql support

---

services/navigation.js

Hidden fields like "created_by" where not being filtered out of related objects. Resulting in objects containing hashed passwords & reset tokens. This change replaces ```"created_by": Object``` with ```"created_by": Id```.
- Checked if project test had not failed
- Applied change in my personal project
- Removed ignore files/folders like .cache/, build/
- Ran npm run develop
- Set rights for  "get", "getById", "render" endpoints to public
- Validated results for "get", "getById", "render" with Postman

Filters out hidden fields from related objects

---

README.md

> Documented content type UID in example config is wrong. This fixes it to the correct format.

docs: fix default content type UID

---

admin/src/pages/View/components/NavigationItemForm/index.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/153
Fixes bug where no labels were displayed in entity dropdown on navigation item form. When no label is available the default label will be created. 
- Create content type with no field of `"title"`, `"name"` or `"subject"`
- Try to add this content type to a new navigation item
- Form should have entities dropdown filled with default labels

fix: no entity labels [CU-23kucmz]

---

README.md
__mocks__/strapi.js
server/controllers/navigation.js
server/graphql/queries/render-navigation.js
server/services/__tests__/functions.test.js
server/services/__tests__/navigation.test.js
server/services/navigation.js
server/services/utils/functions.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/146
> Adds the possibility to render subtree of navigation by providing path param 
- Render navigation tree without providing path param
- Render the whole navigation tree by providing a root path
- Render a subtree of navigation by providing a path to a nested item
- Rendering should return proper items from the navigation tree 
- Rendering works both in REST API and GraphQL
- Rendering works for all render types (tree, rfr and flat)

feat: render by path [CU-21ungpa]

---

server/services/utils/functions.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/159>
PR fixes the isArray error mentioned in the ticket above.
Tested on a fresh installation by both modifying functions.js in node_modules, and installing the forked git repo directly in package.json

fix: isArray not defined error in some use cases

---

server/graphql/types/navigation-item.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/158
> Fixes type of navigation item related field in GraphQL Schema
- Try to render a navigation item with a related field in both Tree and Flat format

fix: related field GraphQL [CU-23tr8vb]

---

admin/src/components/Item/ItemCardHeader/index.js
admin/src/components/Item/index.js
admin/src/components/NavigationItemList/index.js
admin/src/pages/View/index.js
admin/src/utils/index.js

> Introduces drag and drop functionality. Items can change order as long as they are at the same level. 
- It should be possible to drag items around
- It should only be possible to drop items within the same level
- Items order should be saved and after refresh should be the same 
- Dropping the hovering item on the upper part of the target item should place it before the target
- Dropping the hovering item on the lower part of the target item should place it after the target

feat: drag and drop [CU-21mynz7]

---

admin/src/pages/View/components/NavigationItemForm/index.js

> Fixes empty navigation item bug.
The title, when left empty, should be filled with data from a related field.

fix: empty title [CU-2456ye4]

---

admin/src/pages/SettingsPage/index.js

This is a simple change and I just created the PR
Graphql type names can't contain whitespaces. However, in Strapi the display name is a beautified, and human-friendly version of the content type which may contain spaces. This PR ust removes them.
For example, a content type called "Policy Page" will become "PolicyPage" which is the Graphql type that strapi will generate
Pre-patched version
1. Create a content type called "Policy Page" and add it to navigation
2. On restart, Strapi will crash and show this error `Expected Policy Page to be a objectType, saw GraphQLScalarType`
This is because the config saved includes an invalid Graphql type name
After the patch, everything works fine

No whitespace in `navigationItemRelated` Graphql

---

admin/src/pages/View/components/NavigationItemPopup/NavigationItemPopupHeader.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/173
> Fix for the bug mentioned in the ticket. The bug was caused by the ButtonText component which was removed in a newer version of the design system. The component was replaced by the Typography component. 
- Create a project with the newest strapi version. 
- Build and run the project

fix: design system bug

---

server/services/navigation.js

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/186
> Graphql requests of TREE rendering with order field in the request don't fail any more
> All API requests now returned ordered trees as set in Strapi
1. Create a navigation item in Strapi
2. Change ordering of items using drag&drop
3. Test the ordering is right in API responses

ordered trees

---

README.md
server/graphql/types/navigation-item.js
server/services/navigation.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/201
https://github.com/VirtusLab/strapi-plugin-navigation/issues/202
Fixes problems with rendering `related` and `parent` fields. 
**! This PR introduces a breaking change: render API now returns related as a single element instead of an array !**
- Test if response from `/api/navigation/render/` and `/api/navigation/renderChild/` returns correct response 
- Test graphql query :
```
{
renderNavigation(navigationIdOrSlug: "1" ) {
id
parent {
id
}
related{
__typename
... on Post {
title
}
}
}
}
```

fix: graphql fails to render related

---

server/i18n/navigationSetupStrategy.ts
server/services/common.ts

N/A
Covers the corner case for fresh instances of Strapi when:
1. `i18Plugin` is present 
2. There is no custom config set so `i18nEnabled` property is `false` by default
3. No default locale navigation is set
After fixing:
1. Navigation with default locale is going to be set only if no other instances are present in database
2. In addition fixed issue with `publicationState: true` which throws error for Single Types with flow enabled. Looking for `published_at: { $notNull: true }` now
1. Clean DB + fresh Strapi instance
2. Run with empty config
3. See that default navigation is set anyway

fix: create default navigation while bootstrap if missing

---

README.md
__mocks__/strapi.ts
admin/src/components/Item/index.js
package.json
server/graphql/queries/render-navigation-child.js
server/graphql/queries/render-navigation.js
server/graphql/types/index.js
server/graphql/types/navigation-item-related-data.js
server/graphql/types/navigation-item-related.js
server/graphql/types/navigation-item.js
server/graphql/types/navigation-render-type.js
server/i18n/navigationSetupStrategy.ts
server/services/__tests__/service.test.ts
server/services/client.ts
server/services/common.ts
server/utils/constant.ts
types/services.ts
types/utils.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/188
1. Provides coverage for `related.id` in GraphQL queries only like:
```gql
related {
id
attributes {
__typename
... on Page {
Title
}
... on WithFlowType {
Name
}
}
}
```
2. Fixes visibility of `draft` status for types which doesn't have publish flow enabled
3. Aligns the render type enums to `FLAT`, `TREE` and `RFR` for both REST and GQL API
1. Run the app
2. Check your GQL navigation render query for any of content types
3. See that you're now able to get `id` and `attributes` properties
4. Do the same for REST for the same and see no difference in the payload comparing to previous version

fix: CU-2hjq08q - related id in graphql, small refactors and alignments

---

server/i18n/graphQLEnhancers.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/90
- graphql locale param as `I18NLocaleCode` not a `String`
- start strapi
- make GraphQL render navigation query with valid locale (it should work)
- make GraphQL render navigation query with invalid locale (like `"xd"` or simply locale not handled by your instance) (it should not work)

fix: i18n graphql query param as real i18n locale code

---

admin/src/components/Item/index.js
server/graphql/queries/render-navigation.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/90
- Fixes UI bugs with wrapper elements
- Fixes bootstrap errors when strapi doesn't have the I18n plugin installed
- Create a strapi project without the I18n plugin 
- Start project
- Add and save wrapper element (and check if both render and graphql show this new element)
- Add the I18n plugin to the project
- Start the project again
- No errors should appear

fix: wrapper bugs and bootstrap graphql errors

---

admin/src/components/Item/index.js

When editing NavigationItem changing related items is not possible. 
Fixes problem with parsing edited navigation item. 
- Create strapi project
- Test adding and removing navigation items
- Test changing related to different content types and / or different content type entities
- Test editing other navigation item properties 
- No errors should appear

fix: editing related not working

---

admin/src/pages/View/components/NavigationItemForm/index.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/92
Creates a method that fills an empty title with the name of the related entity
- Create strapi project
- Try adding a navigation item with an empty title
- Try emptying the title of an existing item
- In both cases, empty titles should fill out with default values

fix: empty title in navigation item returns error

---

admin/src/pages/View/components/NavigationItemForm/utils/form.js

https://app.clickup.com/t/2jtv9g6
- external path validation extension
- `mailto:` protocol
- `tel:` protocol
Valid telephone numbers
```
123-456-7890
(123) 456-7890
123 456 7890
123.456.7890
+91 (123) 456-7890
+911234567890
123-456-789
(123) 456-789
123 456 789
123.456.789
+91 (123) 456-789
+91123456789
```
- add new external navigation item
- try setting external path as `mailto:test@test.com` or any other mail of your choice
- try setting external path as `mailto:<phone number>`

feat: external path regex extensions [CU-2jtv9g6]

---

server/services/common.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/230
Fixes a bug which prevented single types from multilang usage
tests were made on our companies website which has a mixing of collection and single types. Also we have around 25 pages active and another 20 which are in draft and not linked to navigation.
1. Created navigations item with linking to single and collection types each with two languages
2. Create navigation item with linking to single and collection type with just one language

fix: single type with multiple locale crashs tree and rfr api view

---

server/services/client.ts
server/utils/functions.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/224
Added function that sorts flat structure by order field without ignoring tree structure. 
Create navigation with at least 2 nesting levels.
Flat render of tree like: 
- first parent (order 1)
- first child (order 1)
- second child (order 2)
- second parent (order 2)
should be:
- first parent
- first child
- second child
- second parent

fix: sorting flat structure by order

---

admin/src/pages/SettingsPage/index.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/239
- Fixes bug in the settings page with changing populate param
- Adds possibility to populate media relations
- Run strapi
- Create a content type with relations and media relations 
- Set populate through the settings page for those content types
- Check if render API populates these relations in the result

fix: populate not working with media

---

admin/src/pages/SettingsPage/index.tsx
server/controllers/client.ts
server/services/client.ts
server/services/common.ts
server/utils/functions.ts
types/services.ts
types/utils.ts

Based on:
https://github.com/VirtusLab/strapi-plugin-navigation/issues/239
> Adds possibility to populate related items with URL params. This option overrides populate options configured through the settings page.
- Create project
- Test render endpoints in all types
- Adding populate like in [strapi docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#population) should populate related items fields (like: media, components, localizations, all other relations)

feat: populate with url

---

admin/src/pages/View/components/NavigationItemForm/utils/form.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/254
External navigation items path regexes updates
- shorter telefon numbers are allowed
- longer domain names are allowed
- addresses like `my@example.online` are allowed
- telephone numbers like `+49121212`, `tel:121212` are allowed

fix: external navigation item path regexes

---

server/content-types/navigation-item/schema.ts
server/content-types/navigation/schema.ts

NA
> Fixes the relations between navigation and navigation items. Before this relation created 2 tables with links, but only saved data to one of them. Now this relation uses `mappedBy` and `inversedBy` params to avoid mentioned behavior. 
I've tested this change on two different cases. 
- Clean install, without data
- Migration from the latest install, with data.
No data should disappear. The plugin should work the same on both versions. No output should change in render functions. The only difference should be the lack of `navigations_items_links` table.

fix: wrong relation between navigation and items

---

admin/src/pages/View/components/NavigationItemForm/index.tsx

https://github.com/VirtusLab/strapi-plugin-navigation/issues/277
> Fixed issue with default path value when single type is selected
> Added a better visual preview of the path that will be set after submitting a new navigation item. 
- Create a single content type and add a default path field in settings for this content type
- Try adding a new navigation item without the path field filled
- Try providing the wrong field on the settings page for single content type ( for example field containing spaces in its values )
- Adding a navigation item without a path field filled and with the wrong default field should result in an error in the navigation item form

fix: default path for single types

---

admin/src/components/Item/ItemCardHeader/index.tsx

[https://github.com/VirtusLab/strapi-plugin-navigation/issues/-<your-ticket-#>](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/299)
Handling really long paths by creating max width container.

fix: long path handling on menu ui

---

server/services/common.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/309
Not all Content-Types have the `pluginOptions`. Defaulting to an empty object, otherwise, the plugin fails when it loads

fix(server): default pluginOptions to empty object

---

admin/src/pages/View/components/NavigationItemForm/index.tsx

https://github.com/VirtusLab/strapi-plugin-navigation/issues/341
> What does this PR do/solve?
This PR fix the problem of entity not being selected correctly in the item modal because formik use a string named "related" but compared of Number "id"
> How are you testing the work you're submitting?
I create a menu item in Strapi 4.10 and if i select an entity with linked "path default fields", but not linked with selected entity in modal (before fix), now correctly selected.

fix: bad strict comparision string/number

---

server/config/setupStrategy.ts
server/services/common.ts
server/utils/functions.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/355
Handling of situation when connected to navigation content type is removed from the system.
- settings updated to remove non-existent content types
- when navigation is rendered related items of non-existent content types ignored. error message displayed on such event
- start an app
- create content type
- add item of said content type
- add navigation or navigation item related to newly created content type
- remove create content type
- server should be able to restart
- navigation is updated with clean-up of settings of non-existent content type
- navigation is renderable

fix: deleted related content types

---

admin/src/pages/DataManagerProvider/index.js
admin/src/translations/en.json
server/services/admin.ts
server/services/common.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/361
- when duplication error is encountered descriptive error message is displayed. 
Example:
- minor styling fixes
- build admin static content
- start server
- add navigation for already existing path
- click "save" button
- error message should pop-up

fix: duplicated navigation items error message

---

admin/src/pages/DataManagerProvider/index.js
admin/src/translations/ca.json
admin/src/translations/en.json
admin/src/translations/fr.json

https://github.com/VirtusLab/strapi-plugin-navigation/issues/335
- error message for event of strapi being unable to generate `uiRouterKey` from `title`
- build admin UI
- try to add navigation item with invalid title (example: all characters non-latin)
- try to save
- notification should pop up

feat: invalid slug source notification

---

server/services/client.ts
server/utils/functions.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/366
- fixes for reading navigation by path
- start server
- query for a navigation with root path (or any other you like)
Example:

fix: graphql filtering by path

---

admin/src/pages/View/components/NavigationHeader/index.js
admin/src/translations/ca.json
admin/src/translations/en.json
admin/src/translations/fr.json

https://github.com/VirtusLab/strapi-plugin-navigation/issues/370
- id and slug of navigation displayed in header
- build admin resource
- display navigation details page
- result should be similar to example
- validate displayed `id` and `slug` against details in dev tools' `Network` tab

feat: navigation meta data

---

server/i18n/navigationSetupStrategy.ts
server/services/admin.ts
server/services/common.ts
types/services.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/347
https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/345
DB transactions issues on creating localisations of navigation(s). Parallel db queries were changed to synchronised async calls and bulk operations where possible.
- create navigation with disabled i18n on server (or delete all current navigations)
- start server
- server should be able to startup
- enable i18n
- restart server
- existing navigations should be localised to default locale
- localisations should be created and connected to main navigation
- add new language as supported 
- restart server
- localisations for newly added language should be present
- go to navigation section in admin panel
- add new navigation
- delete newly …

fix: db deadlocks and dup errors

---

server/services/admin.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/378
- On navigation deletion navigation items are manually removed (cascade relation cleanup is not provided by Strapi at the moment)
- create a navigation
- create some navigation items
- check navigation/navigation items status in DB
```sql
select * from navigations;
select * from navigations_items;
```
- remove newly created navigation
- check navigation/navigation items status in DB
- navigation and it's items should be removed

fix: cascade navigation deletion

---

README.md
server/controllers/client.ts
server/routes/client.ts
server/services/client.ts
types/controllers.ts
types/services.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/379
- this PR introduces new endpoint for listing navigations
- make a request (for example: `http://localhost:1337/api/navigation/?locale=en&orderBy=id&orderDirection=DESC`)
- a list of navigations should be returned

feat: read all navigations

---

admin/src/pages/View/components/NavigationItemForm/index.tsx

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/364
- fix for audience being set yet not visible on navigation item form
- start an app
- add audience to navigation item
- save navigation
- reload page
- view navigation item
- set audience should be visible

fix: audience on navigation item

---

server/i18n/navigationSetupStrategy.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/390
In case of adding new locale version previous localisations happend to be disconnected from main one. Because of this bootstrapper tried to create navigations for locale that already exists.
This fix compensates for any connections lost that may happen when adding or removing locale version.
- start server
- add new locale version
- restart server
- restart server
- visit UI navigation section
- new locale version should be added to navigation(s)
- already existing locale version should persist

fix: navigation bootstrap orphan connections

---

admin/src/pages/View/index.js

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/384
Fixes the bug related to unintentional modal closes when not selecting a value from a select inside the navigation item editor modal
Verified by manual testing of the UI.
`@strapi/strapi 4.15.0`
`strapi-plugin-navigation 2.2.16`
1. Open navigation item edit popup (create or edit existing)
2. Open any select component
3. Click inside of the modal but outside of the select
4. Verify that the select is closed but the modal remains open
5. Click outside of the modal
6. Verify that the modal has closed

Add a workaround to prevent unintentional modal closing

---

admin/src/pages/View/components/NavigationItemForm/index.tsx

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/350
Fixes #350. The content type title value was not pulled correctly from the contentTypeEntities-array. The reason was that the comparison against the `related` id failed because one of the values was a string and the other was a number.
`@strapi/strapi 4.15.0`
`strapi-plugin-navigation 2.2.16`
1. Create or edit a navigation item
2. Make sure that the title field is empty
3. Select a related entity with a valid name field configuration
4. Click the save button
5. The navigation item is saved

Fix related entity title parsing bug

---

package.json
server/controllers/client.ts
server/services/common.ts
server/utils/__tests__/functions.test.ts
server/utils/functions.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/401
- populate clause is sanitised
- `createdBy` and `updatedBy` fields are sanitised and entity is also sanitised recursively 
- call api on url like `http://localhost:1337/api/navigation/render/<id>?locale=en&populate=*`
- too permissive clauses should be filtered out

fix: sensitive info leak due to populate field

---

admin/src/components/TextArrayInput/index.tsx
admin/src/pages/SettingsPage/components/CustomFieldForm/index.tsx
admin/src/pages/SettingsPage/components/CustomFieldTable/index.tsx
admin/src/pages/SettingsPage/components/DisableI18nModal/index.tsx
admin/src/pages/SettingsPage/index.tsx
admin/src/pages/SettingsPage/utils/form.ts
admin/src/pages/View/components/NavigationItemForm/index.tsx
admin/src/pages/View/components/NavigationItemForm/types.ts
admin/src/pages/View/components/NavigationItemForm/utils/form.ts
admin/src/pages/View/components/NavigationManager/Form/index.tsx
admin/src/pages/View/utils/types.ts
admin/src/utils/api.ts
jest.config.ts
server/services/client.ts
server/services/common.ts
server/utils/functions.ts
yarn.lock

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/386
Typings issues when building plugin's source code injected into Strapi project.
Context: In recent times Strapi `@strapi/helper-plugin` and other where migrated from JS to TS. This move results in typing declaration files being available for Typescript compiler.
Until now `@strapi/helper-plugin` and other eco-system files where not set as dev dependencies and _ts-ignored_ when impored.
In parent project strapi plugins and helpers are installed and TS declaration are available. Source code typings were not matching what Strapi expects so build was failing.
This PR updates some dependencies also.
- run `yarn`
- run `npm run build`
- build should happen
- copy source code to newly …

fix: typings issues

---

README.md
server/content-types/navigation-item/index.ts
server/content-types/navigation-item/lifecycles.ts
server/content-types/navigation/index.ts
server/content-types/navigation/lifecycles.ts
server/controllers/admin.ts
server/controllers/client.ts
server/graphql/config.ts
server/navigation/setupStrategy.ts
server/services/__tests__/service.test.ts
server/services/admin.ts
server/services/client.ts
server/services/common.ts
server/utils/__tests__/functions.test.ts
server/utils/constant.ts
server/utils/functions.ts
types/controllers.ts
types/index.ts
types/lifecycle.ts
types/services.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/332
- registering lifecycle hooks for navigation and navigation item
- typing refactor for `getPluginService()` function (upfront type specification not longer required)
- run `npm run test:unit`
- specify lifecycle hook(s) as specified in Readme file
- validate hooks being run against your configuration

feat: lifecycle hooks

---

server/i18n/__tests__/utils.test.ts
server/i18n/utils.ts
server/services/__tests__/service.test.ts
server/services/admin.ts
server/services/client.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/396
- fixes for consistency issues in admin's panel
- add a locale (or more than one) 
- restart server
- remove at least one locale from the system
- restart server
- visit `Navigation` panel
- only currently selected locale should be displayed by UI

fix: internalisation issues, locale versions

---

server/i18n/navigationSetupStrategy.ts
server/services/__tests__/service.test.ts
server/services/admin.ts
server/utils/functions.ts
types/services.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/414
On creation of a navigation newly created entity is not visible. This is caused by not connecting newly created entity with a locale. Then in next step navigations with no locale are ignored. In result there's an orphan entity with no connection with i18n.
- go to admin panel
- create a navigation
- newly created navigation should be visible in all navigations list

fix: navigation creation

---

server/services/__tests__/service.test.ts
server/services/admin.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/424
- deleting all navigation items on a navigation delete
context: If a navigation has no items `$or` using an empty list results in all table rows to be included.
- start strapi server
- delete a navigation
- only related navigation items should be deleted

fix: menu items deletion on menu delete

---

admin/src/pages/View/components/NavigationItemForm/index.tsx
admin/src/pages/View/components/NavigationItemForm/types.ts
admin/src/pages/View/components/NavigationItemForm/utils/form.ts
admin/src/pages/View/utils/parsers.js
server/content-types/navigation-item/schema.ts
server/services/client.ts
types/contentTypes.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/432
https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/427
"Read fields from related" is persisted between navigation editions.
- open admin panel
- open navigation details
- add a new item
- set "Read fields from related" to false
- fill navigation item's details
- save
- refresh page
- open navigation item details form
- "Read fields from related" should be set to false

feat: item auto-synce persistence

---

admin/src/pages/HomePage/components/NavigationItemForm/utils/form.ts
admin/src/pages/SettingsPage/components/CustomFieldForm/hooks/index.ts
admin/src/pages/SettingsPage/hooks/index.ts

Form text inputs where not responding correctly to changes in input forms. It was an issue with `values` and `defaultValues` mixed up
- start an app
- edit (or created then edit) navigation item
- change it's title
- title should editable with no issues

fix: form defaults

---

migrations/strapi-plugin-navigation-3.0.0-no-2-locale-slug-regular-slug.ts
server/src/i18n/index.ts
server/src/services/admin/admin.ts

N/A
Navigation slug unified. Locale present in query.
- use migration specified
- all navigation slugs should have locale suffix dropped
- on navigation name edit all locale versions have the same, newly generated slugs

feat: navigation unified slug

---

admin/src/pages/HomePage/components/AdditionalFieldInput/index.tsx

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/468
Boolean additional fields were not editable. Change listener set `value` to `!value` what resulted in `!undefined`
- set boolean additional field
- edit navigation item
- set additional field on navigation item to `false`
- save
- refresh
- field should preserved as `false`

fix: boolean additional fields

---

server/src/graphql/types/navigation-item-related-data.ts
server/src/services/client/client.ts
server/src/services/client/utils.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/472
Items not being available on read (client)
- start an app
- render a navigation
- check if items are available

fix: relation by morph read

---

admin/src/pages/SettingsPage/index.tsx
admin/src/pages/SettingsPage/utils/index.ts
server/src/services/admin/admin.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/462
Restart handling on settings page
- go to plugin's settings page
- save settings
- click restart
- loader should be visible for all of the restart time

fix: server restart on server page

---

admin/src/components/AdditionalFieldInput/index.tsx

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/467
Missing label for media type additional field
- add media additional field to navigation item
- go to navigation form
- add navigation item
- label should be present for media field

fix: missing media type additional file

---

admin/src/api/validators.ts
package.json
server/src/schemas/content-type.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/487
Fixes issue with missing `media` enumeration and `audios` media type.
1. Enable Collection Type with Media field
2. See it works

fix: zod missing media enumeration #487

---

admin/src/pages/HomePage/components/NavigationItemForm/index.tsx
admin/src/pages/SettingsPage/components/CustomFieldTable/index.tsx

https://github.com/VirtusLab/strapi-plugin-navigation/issues/490
Changes the behavior of the `Navigation item type` selector. When there is no `Collection / Single Type` set, the `Internal source` option is not available, but the selector stays enabled for other options.
1. Do not set the Collection / Single type in settings
2. See that you're able to work with navigation items without any issues

fix: behavior of item type selector

---

server/src/repositories/navigation-item.ts
server/src/services/admin/admin.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/461
Unable to remove navigation due navigation items are not removable (`documentId` related issue)
- create a navigation
- add at least one navigation item
- remove navigation
- navigation and navigation items should be removed

fix: deleting navigation

---

server/src/services/client/client.ts
server/src/services/client/types.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/492
- additional fields not rendered in the navigation item. 
- unified way of rendering additional fields for all render types
- set additional fields on navigation item, if not present
- render navigation as `RFR`, `FLAT`, `TREE` and default
- additional fields should be present
- render navigation via GraphQL query
- additional fields should be present

fix: additional fields

---

admin/src/pages/HomePage/components/NavigationItemForm/index.tsx

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/495
Fix for item form error message rendering
- add new navigation item
- select `EXTERNAL` type
- try to save
- external path message should render

fix: navigation item form error message

---

admin/src/components/TextArrayInput/index.tsx

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/494
Setting `select` additional field available options
- go to navigation plugin settings
- add additional field of select type
- set available options
- save settings and restart
- add new navigation item
- set field's value
- save
- render edited navigation
- additional field should be present in the result

fix: select additional field type

---

admin/src/components/icons/navigation.tsx

Change the size of Navigation plugin's menu icon to align with those of Strapi itself, which is 20px.
As it is only a style change, I tested it in the inspector.

fix: unify menu icon size with those of Strapi

---

admin/src/pages/SettingsPage/index.tsx

This console warning is displayed when accessing the Settings page at http://localhost:1337/admin/settings/navigation :
> React does not recognize the `alignItems` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `alignitems` instead. If you accidentally passed it from a parent component, remove it from the DOM element. Error Component Stack
The cause is the presence of invalid attributes on the Box component. These attributes belong to the Flex component, I guess this was a copy-paste mistake.
Open the Settings page, check the developer console of your browser for React errors.

Fix console warning about unknown HTML properties

---

admin/src/pages/HomePage/hooks/index.tsx
admin/src/pages/HomePage/index.tsx
server/src/services/admin/admin.ts
server/src/services/admin/types.ts
server/src/services/admin/utils.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/496
- related field not being copied on fill
- custom fields not being copied on fill
- missing viewId on navigation copied from other locale
- go to `Navigation` view
- have a filled navigation from one locale, and empty for other locale
- have internal items and additional fields on first locale
- fill from other locale
- all required info is copied from the source
- remove a navigation item on newly created navigation
- restore a navigation item on newly created navigation
- save
- refresh view

fix: fill from other locale

---

server/src/services/client/client.ts
server/src/services/common/common.ts
server/src/services/common/types.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/501
Taking into account `contentTypesPopulate` when rendering navigation
- set `contentTypesPopulate` field in navigation
- prepare internal content to have relational fields filled
- render a navigation
- navigation item's related field should be populated as expected

feat: populating navigation item related

---

admin/src/pages/HomePage/components/NavigationItemForm/index.tsx

Fixes #507
https://github.com/VirtusLab/strapi-plugin-navigation/issues/507
The contents of the related content type and related content entity are now sorted by label.
Open the add menu item dialog, observe the sorting in the related content type and entity are now sorted by label.

Sort related content types and entities by name

---

.gitignore
.yarnrc.yml
package.json
yarn.lock

This change adds configuration to support corepack. With corepack, contributors are able to use the precise package manager version that the maintainers also use.
.yarnrc.yml is un-ignored, as it is an important file to make sure that yarn behaves the same everywhere. It is also present in the strapi repository, for instance.
Execute `yarn` and observe the right version being used.

Use corepack to define package manager

---

package.json
yarn.lock

My PR #518 undid the change from #506. I thought putting react-intl in `peerDependencies` would force npm to take the same version as strapi. However, npm selects the latest version of react-intl for strapi-plugin-navigation, so the user again ends up with 2 version. My apologies.

Force react-intl as dependency with fixed version number

---

admin/src/pages/HomePage/components/NavigationItemListItem/index.tsx
server/src/services/client/client.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/516
- external items with children adding enabled
- go to admin panel
- go to navigation screen
- add an external item
- add a child to an external item
- save
- items should be saved
- render changed navigation
- external items should be rendered with their children items

feat: external items with children

---

admin/src/pages/HomePage/components/ControllableCombobox/index.tsx

After 217e6f926568c4ef141900a6d94392ffd0800d85 was released, the combo boxes for the current content type / content item are empty when editing an existing menu item.
Open an existing menu item that was associated with a content item. In 3.0.9 the combo boxes are empty, with this patch they're filled.

fix: combo box not filled when editing a menu item

---

migrations/strapi-plugin-navigation-3.0.0-no-4-additional-fields.js

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/553
As described in the issue way of saving additional fields changed from version to version. A DB migration covers that migration.
- copy migration file to your server 
- check the admin panel

fix: additional boolean fields db migration

---

migrations/strapi-plugin-navigation-3.0.0-no-1-related-id-to-documentid.js

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/551
- id of migration service for id to document id migration
- run migration

fix: migration service id in first migration

---

migrations/strapi-plugin-navigation-3.0.0-no-1-related-id-to-documentid.js
server/src/bootstrap.ts
server/src/repositories/navigation-item.ts
server/src/services/migration/migration.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/549
https://github.com/VirtusLab/strapi-plugin-navigation/issues/550
This PR resolves migration issues during the Strapi v4 to v5 upgrade by deferring custom plugin migrations after Strapi’s internal ones complete. The fix moves the custom migration logic to the `bootstrap` phase, ensuring all system tables and relations (like `*_lnk`, `*_mph`) are properly initialized before any data manipulation occurs.
- Copy the migration file to your server
- Start the server
- Check the admin panel

fix: fix order of first migration

---

admin/src/pages/HomePage/components/NavigationHeader/index.tsx
admin/src/pages/HomePage/index.tsx
server/src/services/common/utils.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/562
- Enables deletion of broken navigation items (with duplicated paths)
- Disables the `Save` button while the server is processing the navigation save request.
**Note**: To delete navigation items, the user must remove all broken items in the branch. For example, if there are three navigation items with the same `path`, the user needs to delete at least two of them. An example is shown in the attached video.
https://github.com/user-attachments/assets/f1066bf2-12ad-4e2f-9b69-99ba1fdc51f7

fix: enable deletion of broken navigation items

---

admin/src/pages/HomePage/components/NavigationItemForm/utils/form.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/560
On switch from `wrapper` to `internal` item, item cannot be saved. This happens for saved items. The issue is `externalPath` field being set to `null`. What is expected is `string` or `undefined`. I made validator to accept ale `null`
- start server
- go to admin
- add a `wrapper` item 
- save navigation
- change `wrapper` item to `internal`
- save item and navigation

fix: internal navigation item ui schema

---

admin/src/pages/HomePage/components/ChangeLanguageDialog/index.tsx
admin/src/pages/HomePage/hooks/index.tsx
admin/src/pages/HomePage/index.tsx
admin/src/translations/en.ts
package.json
server/src/bootstrap.ts
server/src/services/admin/admin.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/567
- creates a new navigation entry with a new locale, when a new language is added to the Strapi Internationalization

fix: update navigation when new locale is created

---

admin/src/api/validators.ts
admin/src/pages/HomePage/components/NavigationItemForm/utils/form.ts
migrations/strapi-plugin-navigation-3.0.0-no-1-related-id-to-documentid.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/577
- Remove dropping tables from the 1st migration as internal Strapi migrations handle them
- Make `path` optional (in the previous version of the plugin, external links had path set to null, which can break loading of the navigation in case of migrating them)
- Run a Strapi with a database in v4 with 1st migration added to `database/migration` folder

fix: migration deletion in wrong order

---

admin/src/pages/HomePage/components/NavigationItemForm/index.tsx
package.json

https://github.com/VirtusLab/strapi-plugin-navigation/issues/596
Enables media search functionality for custom fields in navigation items of type `Wrapper` and `External`, ensuring the Media Library works consistently across all navigation item types.
- add a custom field in type media
- go to the add navigation item form
- change the navigation item type to `wrapper` or `external`
- try to add media
- check if you can search in media library input

fix: search in media library
