VirtusLab-Open-Source/strapi-plugin-navigation

admin/src/containers/View/utils/parsers.js
services/navigation.js

None
Solves the issue with non-updating polymorphic relation with content type.
1. Link the plugin
2. See that you're able to change the relation, save it, again and again all is getting updated

fix: polymorphic relation update

---

controllers/navigation.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/13
Fixes reported issue with UUIDs as identifiers.
NoN

fix: issue #13 fix for uuid parsing from props

---

admin/src/components/Item/CardWrapper.js
admin/src/components/Item/index.js
admin/src/components/List/index.js
admin/src/containers/DataManagerProvider/index.js
admin/src/containers/DataManagerProvider/reducer.js
admin/src/containers/View/index.js
services/navigation.js

Display error path when we detect duplicate path. 
Example:

Feature: Display error path

---

admin/src/components/Item/CardItem.js
admin/src/components/Item/CardItemLevelAdd.js
admin/src/components/Item/CardItemTitle.js
admin/src/components/Item/CardWrapper.js
admin/src/components/Item/index.js
admin/src/components/ItemFooter/index.js
admin/src/containers/View/FadedWrapper.js
admin/src/containers/View/Wrapper.js
admin/src/containers/View/utils/parsers.js
controllers/navigation.js

Fix: Mark items on duplicate path

---

admin/src/components/ItemFooter/index.js
admin/src/containers/DataManagerProvider/index.js
admin/src/containers/View/components/NavigationItemForm/index.js
admin/src/containers/View/components/NavigationItemForm/utils/form.js
admin/src/containers/View/components/NavigationItemPopup/index.js
admin/src/containers/View/index.js
admin/src/containers/View/utils/parsers.js
controllers/navigation.js
services/navigation.js
services/utils/functions.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/23
> Fix problems with adding single types to navigation items. This PR resolve this problem on SQL database and mongo.
Try to add elements with relation to a single type on SQL database and mongo, you should can, and in response you should get correctly relation items.

feat: single content type support - small fixes

---

admin/src/containers/View/utils/parsers.js
services/navigation.js

Fix: Problem with related field

---

services/utils/functions.js

Fix: Disable limit on fetch content types for render

---

__mocks__/helpers/home-page.settings.json
__mocks__/helpers/my-homepage.settings.json
__mocks__/helpers/strapi.js
package.json
services/__tests__/navigation.test.js
services/navigation.js
yarn.lock

https://github.com/VirtusLab/strapi-plugin-navigation/issues/68
- extends the approach proposed by @simpian in PR #69 and fully solves issue #68
- improves tests coverage
- play with your content types and their routing config, all should work as expected

fix: endpoints for custom routes content types are undefined

---

.github/stale.yml

Add [stale](https://github.com/apps/stale) configuration to project

feat: add stale bot configuration

---

services/navigation.js

Fix problems with not defined filter in renderType method

fix: add filter params in render type method

---

__mocks__/helpers/strapi.js
admin/src/containers/View/utils/parsers.js
config/functions/bootstrap.js
controllers/navigation.js
models/navigationItem.settings.json
models/navigations_items_related.js
models/navigations_items_related.settings.json
services/__tests__/navigation.test.js
services/navigation.js
services/utils/functions.js

feat: remove polymorphic relation

---

README.md
config/schema.graphql.js
services/navigation.js

fix: migrate configs to `plugins.js`

---

admin/src/pages/DataManagerProvider/index.js
admin/src/pages/DataManagerProvider/reducer.js

fix: remove immutable from plugin

---

config/schema.graphql.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/103
Fixes bug in GraphQL integration with the plugin 
Test fetching navigation item related with GraphQL

fix: graphql navigation item related

---

README.md
server/services/navigation.js

- Updates documentation to be compatible with the new version of the plugin.
- Fixes minor bug with rendering navigation.

docs: strapi v4

---

admin/src/components/ConfirmationDialog/index.js
admin/src/components/Item/ItemCardHeader/index.js
admin/src/components/Item/index.js
admin/src/pages/SettingsPage/index.js
admin/src/pages/View/components/NavigationHeader/index.js
server/services/utils/functions.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/177

fix: drag and drop firefox bug [CU-29gnytc]

---

admin/src/pages/View/components/NavigationItemForm/index.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/180
> Changes condition for form validation taking into account single types
- Add internal navigation item with a related single type

fix: savign single types [CU-29pe9y6]

---

admin/src/components/Item/index.js
admin/src/pages/DataManagerProvider/index.js
admin/src/pages/View/components/NavigationItemForm/index.js
admin/src/pages/View/utils/parsers.js
server/services/navigation.js

[Issues with single types #182](https://github.com/VirtusLab/strapi-plugin-navigation/issues/182)
- Add navigation item with single type related
- Save the item
- Submit the navigation 
- Edit the added item 
- Remove the added item
All actions should be successfull

fix: single types patch

---

admin/src/components/Alert/styles.js
admin/src/components/Item/ItemCardHeader/index.js
admin/src/pages/SettingsPage/index.js
admin/src/pages/View/utils/parsers.js
admin/src/translations/en.json
server/services/navigation.js

https://github.com/VirtusLab/strapi-plugin-navigation/issues/189
https://github.com/VirtusLab/strapi-plugin-navigation/issues/192
Fixes issues with disappearing single types on a setting page and some issues with saving related single types on MySQL
- check that single types are working as expected

fix: issues #192 #189 disappearing single types

---

README.md
package.json
server/bootstrap/index.ts
server/graphql/config.ts
server/graphql/queries/render-navigation-child.js
server/graphql/queries/render-navigation.js
server/graphql/setupStrategy.ts
server/graphql/types/content-types-name-fields.js
server/services/admin.ts
server/services/common.ts
server/utils/functions.ts
types/bootstrap.ts
types/services.ts
yarn.lock

https://github.com/VirtusLab/strapi-plugin-navigation/issues/79
> Implements basic integration with strapi webhooks
1. Create webhook in strapi that responds to entry.create or entry.update
2. Update navigation 
3. Check if webhooks has been triggered

feat: basic webhooks integration [CU-21mwpq0]

---

server/controllers/client.ts
server/navigation/setupStrategy.ts

https://app.clickup.com/t/2jtv9cv
- fix for server crash on navigation bootstrap when app is clean slate and navigation plugin is enabled
- TODO

fix: pre-release fixes

---

admin/src/pages/View/components/NavigationItemForm/utils/form.js

None
Resolving merge issue for PR `master` <- `develop`

chore: update with master

---

admin/src/pages/DataManagerProvider/index.js
admin/src/pages/View/components/NavigationManager/AllNavigations/icons.tsx
admin/src/pages/View/components/NavigationManager/AllNavigations/index.tsx
admin/src/pages/View/components/NavigationManager/DeletionConfirm/index.tsx
admin/src/pages/View/components/NavigationManager/ErrorDetails/index.tsx
admin/src/pages/View/components/NavigationManager/Footer/index.tsx
admin/src/pages/View/components/NavigationManager/Form/index.tsx
admin/src/pages/View/components/NavigationManager/NavigationUpdate/index.tsx
admin/src/pages/View/components/NavigationManager/NewNavigation/index.tsx
admin/src/pages/View/components/NavigationManager/index.tsx
admin/src/pages/View/components/NavigationManager/types.ts
admin/src/translations/en.json
types/utils.ts

None
Implementation of missing review items from: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/pull/221
- admin can list all navigation
- admin can create new navigation
- admin can change navigation's visibility
- admin can delete navigation(s)

refactor: navigation manager reworks

---

admin/src/pages/DataManagerProvider/index.js
admin/src/pages/SettingsPage/index.js
admin/src/pages/View/components/NavigationManager/AllNavigations/icons.tsx
admin/src/pages/View/components/NavigationManager/AllNavigations/index.tsx
admin/src/pages/View/components/NavigationManager/DeletionConfirm/index.tsx
admin/src/pages/View/components/NavigationManager/ErrorDetails/index.tsx
admin/src/pages/View/components/NavigationManager/Footer/index.tsx
admin/src/pages/View/components/NavigationManager/Form/index.tsx
admin/src/pages/View/components/NavigationManager/NavigationUpdate/index.tsx
admin/src/pages/View/components/NavigationManager/NewNavigation/index.tsx
admin/src/pages/View/components/NavigationManager/index.tsx
admin/src/pages/View/components/NavigationManager/types.ts
admin/src/translations/en.json
server/services/client.ts
server/utils/functions.ts
types/utils.ts

chore: rebase master

---

server/services/common.ts
server/utils/functions.ts
yarn.lock

https://github.com/VirtusLab/strapi-plugin-navigation/issues/246
> Adds populate field in template name factory

fix: populate template in template name factory

---

README.md
__mocks__/strapi.ts
admin/src/pages/DataManagerProvider/index.js
admin/src/pages/SettingsPage/types.ts
admin/src/pages/View/components/NavigationItemForm/index.tsx
admin/src/pages/View/components/NavigationItemForm/types.ts
admin/src/pages/View/components/NavigationItemPopup/index.js
admin/src/pages/View/index.js
package.json
server/config/index.ts
server/config/setupStrategy.ts
server/controllers/admin.ts
server/routes/admin.ts
server/services/admin.ts
server/services/client.ts
server/services/common.ts
types/config.ts
types/controllers.ts
types/services.ts
yarn.lock

https://app.clickup.com/t/2q95fwv
Unification of slugging logic. Opening this logic for extending (see: README.md).
- Slugger available as a controller
- Slugger available as a service
Depends on: https://github.com/VirtusLab-Open-Source/strapi-typed/pull/13
Things should work the same. Changes should be transparent for current development experience.

feat: slugifying approach change [CU-2q95fwv]

---

admin/src/index.js
admin/src/pages/SettingsPage/components/CustomFieldForm/index.tsx
admin/src/pages/SettingsPage/index.tsx
admin/src/pages/SettingsPage/utils/form.ts
admin/src/pages/View/components/NavigationItemForm/index.tsx
admin/src/pages/View/components/NavigationItemForm/utils/form.ts
admin/src/pages/View/index.js
admin/src/translations/en.json

fixes: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/267
- Chunk name changed for App component
- Better display error messages
- Disable submitting navigation items with wrong related
- Better sorting
- All select inputs in navigations forms should be sorted alphabetically 
- Navigation script chunk name should be changed 
- Should not be possible to leave the related field empty after selecting the collection type in NavigationItemForm
- If any relation is empty in navigation error should be displayed

fix: fixes for master

---

package.json

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/292
Expand on supported to Node v18. 
No functionality is introduced.

chore: supported node version update

---

admin/src/pages/View/index.js
package.json

https://github.com/VirtusLab/strapi-plugin-navigation/issues/276
Changes search to case insensitive
1. Run the app
2. Try to search using case sensitive / case insensitive approach

[CU-862hxegk3] Case insensitive search

---

README.md
admin/src/pages/DataManagerProvider/index.js
admin/src/pages/SettingsPage/index.tsx
admin/src/pages/View/index.js
server/routes/admin.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/315
Fixes lack of security policies on admin endpoints.
Extends the documentation with RBAC + Tokens explanation.
1. Use different permissions for admin users
2. See that you're not able to call admin endpoints without proper permissions as well

fix: issue #315 - provide endpoint policies

---

README.md

fix type in README

---

README.md
admin/src/pages/View/components/NavigationItemForm/index.tsx
package.json
yarn.lock

https://github.com/VirtusLab/strapi-plugin-navigation/issues/346
Fixes default title fetching for Single Types
1. Run Strapi
2. Configure default titles per types via the Settings Page
3. Add item with on of your Collection Types
4. Add item with one of your Single Types
5. Save each
6. See that titles are fetched properly

fix: issue #346 fetching default title

---

package.json
server/src/i18n/index.ts
server/tsconfig.json

https://app.clickup.com/t/8695xubyr
- fallback for at least one navigation available
- zod typing issues
- delete all navigations.
- start strapi
- after bootstrap navigation is present

fix: fallback main navigation [CU-8695xubyr]

---

jest.config.ts
package.json
server/src/config/index.ts
server/src/controllers/admin.ts
server/src/controllers/client.ts
server/src/schemas/config.ts
server/src/utils/constants.ts
server/src/utils/functions.ts
server/tests/config/setup.test.ts
server/tests/content-types/audience.test.ts
server/tests/content-types/navigation-item.test.ts
server/tests/content-types/navigation.test.ts
server/tests/controllers/admin.test.ts
server/tests/controllers/client.test.ts
server/tests/utils.ts
server/tests/utils/functions.test.ts

Missing tests added
- `yarn test:unit`

chore: tests pack

---

admin/src/pages/HomePage/components/NavigationManager/Footer/index.tsx
admin/src/pages/HomePage/components/NavigationManager/Form/hooks.ts
admin/src/pages/HomePage/components/NavigationManager/Form/index.tsx
admin/src/pages/HomePage/components/NavigationManager/NavigationUpdate/index.tsx
admin/src/pages/HomePage/components/NavigationManager/NewNavigation/index.tsx
admin/src/pages/HomePage/components/NavigationManager/index.tsx
admin/src/pages/HomePage/components/NavigationManager/types.ts
admin/src/pages/SettingsPage/index.tsx
admin/src/translations/en.ts
admin/src/translations/fr.ts
package.json
yarn.lock

feat: nav form on strapi

---

admin/src/api/validators.ts
admin/src/pages/HomePage/components/NavigationItemForm/index.tsx
admin/src/pages/HomePage/components/NavigationItemForm/utils/form.ts
admin/src/pages/HomePage/components/NavigationItemListItem/index.tsx
admin/src/pages/HomePage/utils/parsers.ts
server/src/services/client/client.ts

N/A
`Wrapper` navigation item type restored
- start server
- display navigation tree
- add new item
- wrapper item should be available
- save
- read navigation through API
- `wrapper` type items should be rendered

feat: navigation item wrapper type restored

---

admin/src/api/validators.ts
admin/src/pages/HomePage/components/NavigationItemForm/index.tsx
admin/src/pages/HomePage/components/NavigationItemListItem/index.tsx
admin/src/pages/HomePage/utils/parsers.ts
migrations/strapi-plugin-navigation-3.0.0-no-3-morph-relation.js
server/src/content-types/navigation-item/schema.ts
server/src/dtos/navigation-item.ts
server/src/repositories/generic.ts
server/src/repositories/navigation-item.ts
server/src/repositories/navigation.ts
server/src/schemas/navigation.ts
server/src/services/admin/admin.ts
server/src/services/admin/utils.ts
server/src/services/client/client.ts
server/src/services/client/utils.ts
server/src/services/common/common.ts
server/src/services/migration/migration.ts
server/tests/content-types/navigation-item.test.ts

CU-8695xu9r9
Navigation item related item handled by morph
- run migration
- start an app
- no functional changes should be present

feat(8695xu9r9): related handled by morph

---

admin/src/pages/HomePage/components/NavigationItemForm/index.tsx
admin/src/translations/ca.ts
admin/src/translations/en.ts
admin/src/translations/fr.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/464
Navigation item refactor. Screenshots below
- enter admin panel
- select navigation view
- add/edit navigation item

refactor: navigation item form

---

admin/src/pages/HomePage/components/NavigationItemListItem/index.tsx
yarn.lock

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/515
- new item order on add
- go to navigation view
- add an item (first)
- add another item (second)
- second item should be added after first one

fix: item order on add

---

admin/src/pages/HomePage/components/NavigationItemForm/utils/form.ts

https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/511
- relative external paths
- go to navigation screen
- add an external item
- type in a relative path
- add other required information
- save
- save the navigation
- no validation error should be displayed

feat: relative external paths

---

README.md
admin/src/pages/HomePage/components/NavigationItemForm/index.tsx
admin/src/pages/HomePage/components/NavigationItemListItem/index.tsx
package.json
server/src/config/setup.ts
server/src/services/admin/admin.ts
server/src/services/common/common.ts
yarn.lock

https://github.com/VirtusLab/strapi-plugin-navigation/issues/524
https://github.com/VirtusLab/strapi-plugin-navigation/issues/526
https://github.com/VirtusLab/strapi-plugin-navigation/issues/527
Multiple issues related to content type settings and selection of their entities in Navigation Item.

fix: content type settings (#526), selecting entities (#527, #524)

---

admin/src/pages/HomePage/components/ControllableCombobox/index.tsx
admin/src/pages/HomePage/components/NavigationItemForm/index.tsx
package.json
yarn.lock

https://github.com/VirtusLab/strapi-plugin-navigation/issues/530
Fixing an issue with adding the Entity to nav items in version 3.0.8.

fix: allow to select entities (#530)

---

admin/src/pages/HomePage/components/AdditionalFieldInput/index.tsx
package.json
yarn.lock

https://github.com/VirtusLab/strapi-plugin-navigation/issues/540
- Add the ability to clear a custom field in the `media` type if it's not required.

fix: fix clear media custom field

---

admin/src/translations/fr.ts

Just a few improvements regarding French translation (punctation and minor wording)

Update French translation

---

README.md
server/src/config/index.ts

https://github.com/VirtusLab/strapi-plugin-navigation/issues/547
- removed `i18nEnabled` property from the code
- updated `Readme`

fix: remove i18n
